[workspace]
authors = ["Eastnoob <61303573+eastnoob@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "LayoutTask_Player"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
install-js = "npm install"
dev = "npm run dev"
build = "npm run build"
test = "npm run test"
test-watch = "npm run test:watch"
preview = "npm run preview"

[dependencies]
nodejs = ">=22,<23"
